# Generated by Django 3.2.6 on 2022-06-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активен'),
        ),
    ]
