# Generated by Django 3.2.6 on 2022-06-05 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actionsapp', '0002_action_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='create_timestamp',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='update_timestamp',
            new_name='updated',
        ),
    ]
