# Generated by Django 3.2.6 on 2022-06-05 11:14

from django.db import migrations


def copy_price_to_basic(apps, schema_editor):
    Products = apps.get_model('mainapp', 'Products')
    for product in Products.objects.all():
        product.basic_price = product.price
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_products_basic_price'),
    ]

    operations = [
        migrations.RunPython(copy_price_to_basic),
    ]