# Generated by Django 3.2.6 on 2022-05-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_alter_user_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='langs',
            field=models.CharField(blank=True, max_length=128, verbose_name='языки'),
        ),
    ]
